# Generated by Django 6.0 on 2026-01-06 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='capacidad_disponible',
            field=models.PositiveIntegerField(default=0, verbose_name='Capacidad disponible'),
        ),
    ]
