# Generated by Django 6.0 on 2026-01-07 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_area_capacidad_disponible'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=150, verbose_name='Apellidos')),
                ('correo', models.EmailField(max_length=254, unique=True, verbose_name='Correo')),
                ('contraseña', models.CharField(max_length=128, verbose_name='Contraseña')),
                ('telefono', models.CharField(blank=True, max_length=30, null=True, verbose_name='Teléfono')),
                ('numero_empleado', models.PositiveIntegerField(unique=True, verbose_name='Número de empleado')),
                ('rol', models.CharField(max_length=50, verbose_name='Rol')),
                ('puesto', models.CharField(max_length=100, verbose_name='Puesto')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
    ]
