# Generated by Django 6.0 on 2026-01-07 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='puesto',
            field=models.CharField(choices=[('EDIFICIO', 'Edificio'), ('ENTRADA_PEATONAL', 'Entrada peatonal'), ('ENTRADA_VEHICULAR', 'Entrada vehicular'), ('CAFETERIA', 'Cafetería'), ('ESTACIONAMIENTO', 'Estacionamiento')], max_length=30, verbose_name='Puesto'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='rol',
            field=models.CharField(choices=[('JEFE_AREA', 'Jefe de área'), ('GUARDIA', 'Guardia'), ('PATRULLA', 'Patrulla')], default='GUARDIA', max_length=20, verbose_name='Rol'),
        ),
    ]
