# Generated by Django 6.0 on 2026-01-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_empleado_puesto_alter_empleado_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellidos', models.CharField(
                    max_length=150, verbose_name='Apellidos')),
                ('matricula', models.CharField(max_length=50,
                 unique=True, verbose_name='Matrícula')),
                ('correo', models.EmailField(max_length=254,
                 unique=True, verbose_name='Correo')),
                ('telefono', models.CharField(blank=True,
                 max_length=30, null=True, verbose_name='Teléfono')),
                ('contraseña', models.CharField(
                    max_length=128, verbose_name='Contraseña')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
    ]
