# Generated by Django 6.0 on 2026-01-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=20,
                 unique=True, verbose_name='Placa')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('color', models.CharField(max_length=30, verbose_name='Color')),
                ('tipo_vehiculo', models.CharField(choices=[('AUTOMOVIL', 'Automóvil'), ('MOTOCICLETA', 'Motocicleta'), (
                    'OTRO', 'Otro')], default='AUTOMOVIL', max_length=20, verbose_name='Tipo de vehículo')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
            },
        ),
    ]
