# Generated by Django 6.0 on 2026-01-08 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_vehiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='vehiculos', to='app.usuario', verbose_name='Usuario'),
        ),
    ]
