# Generated by Django 6.0 on 2026-01-09 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_dispositivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Espacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=50, unique=True, verbose_name='Clave')),
                ('estado', models.CharField(choices=[('OCUPADO', 'Ocupado'), ('LIBRE', 'Libre')], default='LIBRE', max_length=10, verbose_name='Estado')),
                ('discapacitado', models.BooleanField(default=False, verbose_name='Discapacitado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='espacios', to='app.area', verbose_name='Área')),
            ],
            options={
                'verbose_name': 'Espacio',
                'verbose_name_plural': 'Espacios',
            },
        ),
    ]
