# Generated by Django 6.0 on 2026-01-09 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_espacio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='capacidad_disponible',
        ),
        migrations.RemoveField(
            model_name='area',
            name='capacidad_total',
        ),
    ]
