# Generated by Django 6.0 on 2026-01-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_area_capacidad_disponible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='espacio',
            name='roi',
            field=models.JSONField(blank=True, null=True, verbose_name='ROI'),
        ),
    ]
