# Generated by Django 6.0 on 2026-01-10 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_espacio_roi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='espacio',
            name='roi',
        ),
        migrations.AddField(
            model_name='usuario',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='app.area', verbose_name='Área'),
        ),
    ]
