# Generated by Django 6.0 on 2026-01-11 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_espacio_roi_usuario_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=200, verbose_name='Título')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversaciones_chat', to='app.usuario', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Conversación de chat',
                'verbose_name_plural': 'Conversaciones de chat',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('respuesta', models.TextField(verbose_name='Respuesta')),
                ('tiempo_ms', models.PositiveIntegerField(verbose_name='Tiempo de respuesta (ms)')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='app.chatconversation', verbose_name='Conversación')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes_chat', to='app.usuario', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Mensaje de chat',
                'verbose_name_plural': 'Mensajes de chat',
            },
        ),
    ]
