# Generated by Django 6.0 on 2026-01-11 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_chatconversation_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ACCESO_AUTORIZADO', 'Acceso autorizado'), ('SALIDA', 'Salida'), ('OTRO', 'Otro')], default='OTRO', max_length=30, verbose_name='Tipo')),
                ('cuerpo', models.CharField(max_length=255, verbose_name='Cuerpo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('leido', models.BooleanField(default=False, verbose_name='Leído')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to='app.usuario', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
            },
        ),
    ]
